import { useEffect, useState } from 'react';
import { get, post } from '../api';
const money=v=>`Bs. ${Number(v||0).toFixed(2)}`;
export default function Cash({user}){
 const [current,setCurrent]=useState(undefined);const [sessions,setSessions]=useState([]);const [opening,setOpening]=useState(0);const [movement,setMovement]=useState({movement_type:'expense',amount:'',concept:'',note:''});const [declared,setDeclared]=useState('');const [message,setMessage]=useState('');
 async function load(){try{const [c,s]=await Promise.all([get('/cash/current'),get('/cash/sessions')]);setCurrent(c.session);setSessions(s.sessions);}catch(e){setMessage(e.message);}}
 useEffect(()=>{load();},[]);
 async function open(){try{await post('/cash/open',{opening_amount:Number(opening)});setMessage('Caja abierta.');await load();}catch(e){setMessage(e.message);}}
 async function addMovement(){try{await post('/cash/movement',{...movement,amount:Number(movement.amount)});setMovement({...movement,amount:'',concept:'',note:''});setMessage('Movimiento registrado.');await load();}catch(e){setMessage(e.message);}}
 async function close(){if(!confirm('¿Cerrar tu caja? Después deberás abrir una nueva para seguir vendiendo.'))return;try{const r=await post('/cash/close',{declared_amount:Number(declared)});setMessage(`Caja cerrada. Diferencia: ${money(r.difference_amount)}`);setDeclared('');await load();}catch(e){setMessage(e.message);}}
 if(current===undefined)return <div className="skeleton-block"/>;
 return <div className="page-stack">
  {message&&<div className="inline-alert">{message}</div>}
  {!current?<section className="cash-open-card"><span className="eyebrow">INICIO DE TURNO</span><h2>Abre tu caja para comenzar</h2><p>Registra el efectivo con el que recibes la caja. Las ventas del turno quedarán asociadas a tu usuario.</p><label>Fondo inicial<div className="money-input"><span>Bs.</span><input type="number" value={opening} onChange={e=>setOpening(e.target.value)}/></div></label><button className="primary-button" onClick={open}>Abrir caja</button></section>:<>
   <section className="stats-grid four"><article className="stat-card primary"><span>Venta total del turno</span><strong>{money(current.summary.sales_total)}</strong><small>{current.summary.sales_count} ventas</small></article><article className="stat-card"><span>Efectivo esperado</span><strong>{money(current.summary.expected_cash)}</strong><small>incluye fondo inicial</small></article><article className="stat-card"><span>Otros ingresos</span><strong>{money(current.summary.other_income)}</strong><small>movimientos manuales</small></article><article className="stat-card"><span>Egresos</span><strong>{money(current.summary.expenses)}</strong><small>movimientos manuales</small></article></section>
   <div className="two-panels"><section className="panel"><div className="panel-head"><div><span className="eyebrow">MOVIMIENTOS</span><h3>Ingreso o egreso</h3></div></div><div className="form-grid"><label>Tipo<select className="input" value={movement.movement_type} onChange={e=>setMovement(m=>({...m,movement_type:e.target.value}))}><option value="expense">Egreso</option><option value="income">Ingreso</option></select></label><label>Monto<input className="input" type="number" value={movement.amount} onChange={e=>setMovement(m=>({...m,amount:e.target.value}))}/></label><label>Concepto<input className="input" value={movement.concept} onChange={e=>setMovement(m=>({...m,concept:e.target.value}))} placeholder="Ej. Compra de hielo"/></label><button className="secondary-button" disabled={!movement.amount||!movement.concept} onClick={addMovement}>Registrar movimiento</button></div></section>
   <section className="panel danger-zone"><div className="panel-head"><div><span className="eyebrow">FIN DE TURNO</span><h3>Cerrar caja</h3></div></div><p>Cuenta el efectivo físico e ingresa el total. El sistema calculará automáticamente cualquier diferencia.</p><label>Efectivo contado<div className="money-input"><span>Bs.</span><input type="number" value={declared} onChange={e=>setDeclared(e.target.value)}/></div></label><button className="danger-button" disabled={declared===''} onClick={close}>Cerrar mi caja</button></section></div>
  </>}
  <section className="panel flat"><div className="panel-head"><div><span className="eyebrow">HISTORIAL</span><h3>{user.role==='admin'?'Cajas recientes':'Mis cajas recientes'}</h3></div></div><div className="responsive-table"><table><thead><tr><th>Usuario</th><th>Apertura</th><th>Cierre</th><th>Inicial</th><th>Ventas</th><th>Esperado</th><th>Diferencia</th><th>Estado</th></tr></thead><tbody>{sessions.map(s=><tr key={s.id}><td><strong>{s.user_name}</strong></td><td>{new Date(s.opened_at.replace(' ','T')).toLocaleString('es-BO')}</td><td>{s.closed_at?new Date(s.closed_at.replace(' ','T')).toLocaleString('es-BO'):'—'}</td><td>{money(s.opening_amount)}</td><td>{money(s.sales_total)}</td><td>{s.expected_amount!==null?money(s.expected_amount):money(s.live_expected_amount)}</td><td className={Number(s.difference_amount)<0?'negative':''}>{s.difference_amount!==null?money(s.difference_amount):'—'}</td><td><span className={`stock-pill ${s.status==='open'?'ok':'neutral'}`}>{s.status==='open'?'Abierta':'Cerrada'}</span></td></tr>)}</tbody></table></div></section>
 </div>;
}
