import { useEffect, useState } from 'react';
import { get, post, put } from '../api';
import Modal from '../components/Modal';
import { UserPlus } from 'lucide-react';
export default function Users(){
 const [users,setUsers]=useState([]);const [open,setOpen]=useState(false);const [selected,setSelected]=useState(null);const [message,setMessage]=useState('');
 async function load(){try{const r=await get('/users');setUsers(r.users);}catch(e){setMessage(e.message);}}
 useEffect(()=>{load();},[]);
 return <div className="page-stack"><section className="page-intro"><div><p>Cajeros y administradores. Cada acción importante queda vinculada a un usuario.</p></div><button className="primary-button small" onClick={()=>setOpen(true)}><UserPlus size={16}/>Nuevo usuario</button></section>{message&&<div className="inline-alert">{message}</div>}<section className="panel flat"><div className="responsive-table"><table><thead><tr><th>Nombre</th><th>Usuario</th><th>Rol</th><th>Último acceso</th><th>Estado</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.name}</strong></td><td>@{u.username}</td><td>{u.role_label}</td><td>{u.last_login_at?new Date(u.last_login_at.replace(' ','T')).toLocaleString('es-BO'):'Nunca'}</td><td><span className={`stock-pill ${Number(u.active)?'ok':'neutral'}`}>{Number(u.active)?'Activo':'Inactivo'}</span></td><td><button className="text-button" onClick={()=>setSelected(u)}>Editar</button></td></tr>)}</tbody></table></div></section><NewUser open={open} onClose={()=>setOpen(false)} onSaved={async m=>{setMessage(m);setOpen(false);await load();}}/><EditUser user={selected} onClose={()=>setSelected(null)} onSaved={async m=>{setMessage(m);setSelected(null);await load();}}/></div>;
}
function NewUser({open,onClose,onSaved}){const [f,setF]=useState({name:'',username:'',password:'',role:'cashier'});const [err,setErr]=useState('');async function save(){try{await post('/users',f);onSaved('Usuario creado.');}catch(e){setErr(e.message);}}return <Modal open={open} title="Nuevo usuario" subtitle="Crea un acceso para caja o administración" onClose={onClose}><div className="form-grid"><label>Nombre<input className="input" value={f.name} onChange={e=>setF(x=>({...x,name:e.target.value}))}/></label><label>Usuario<input className="input" value={f.username} onChange={e=>setF(x=>({...x,username:e.target.value}))}/></label><label>Contraseña<input className="input" type="password" value={f.password} onChange={e=>setF(x=>({...x,password:e.target.value}))}/></label><label>Rol<select className="input" value={f.role} onChange={e=>setF(x=>({...x,role:e.target.value}))}><option value="cashier">Cajero</option><option value="admin">Administrador</option></select></label></div>{err&&<div className="inline-alert danger">{err}</div>}<button className="primary-button" onClick={save}>Crear usuario</button></Modal>}
function EditUser({user,onClose,onSaved}){const [f,setF]=useState({});const [err,setErr]=useState('');useEffect(()=>{if(user)setF({name:user.name,role:user.role,active:Boolean(Number(user.active)),password:''});},[user]);if(!user)return null;async function save(){try{await put(`/users/${user.id}`,f);onSaved('Usuario actualizado.');}catch(e){setErr(e.message);}}return <Modal open title={user.name} subtitle={`@${user.username}`} onClose={onClose}><div className="form-grid"><label>Nombre<input className="input" value={f.name||''} onChange={e=>setF(x=>({...x,name:e.target.value}))}/></label><label>Rol<select className="input" value={f.role||'cashier'} onChange={e=>setF(x=>({...x,role:e.target.value}))}><option value="cashier">Cajero</option><option value="admin">Administrador</option></select></label><label>Nueva contraseña<input className="input" type="password" placeholder="Dejar vacío para no cambiar" value={f.password||''} onChange={e=>setF(x=>({...x,password:e.target.value}))}/></label><label className="check-row"><input type="checkbox" checked={Boolean(f.active)} onChange={e=>setF(x=>({...x,active:e.target.checked}))}/>Usuario activo</label></div>{err&&<div className="inline-alert danger">{err}</div>}<button className="primary-button" onClick={save}>Guardar cambios</button></Modal>}
